site_name: Your Documentation
site_author: Devansh Agarwal, Kshitij Agarwal
docs_dir: docs
site_description: 'Your Documentation'

theme:
        name: material
        palette:
                scheme: slate
                primary: indigo

repo_name: your
repo_url: https://github.com/devanshkv/your

nav:
        - Core: sources/your.md
        - Candidate: sources/candidate.md
        - Utils:
                  - RFI: sources/utils/rfi.md
                  - Astro: sources/utils/astro.md
                  - Plotter: sources/utils/plotter.md
                  - Heimdall: sources/utils/heimdall.md
                  - Math: sources/utils/math.md

markdown_extensions:
        - pymdownx.emoji:
                  emoji_index: !!python/name:materialx.emoji.twemoji
                  emoji_generator: !!python/name:materialx.emoji.to_svg
        - codehilite:
                  guess_lang: False
                  use_pygments: True