site_name: Your Documentation
site_author: Devansh Agarwal, Kshitij Agarwal
docs_dir: sources
site_description: 'Your Documentation'

theme:
        name: material
        palette:
                scheme: slate
                primary: indigo

repo_name: your
repo_url: https://github.com/devanshkv/your

nav:
  - Core: your.md
  - Candidate: candidate.md
  - Utils:
      - RFI: utils/rfi.md
      - Astro: utils/astro.md
      - Plotter: utils/plotter.md
      - Heimdall: utils/heimdall.md
      - Math: utils/math.md

markdown_extensions:
        - pymdownx.emoji:
                  emoji_index: !!python/name:materialx.emoji.twemoji
                  emoji_generator: !!python/name:materialx.emoji.to_svg
        - codehilite:
                  guess_lang: False
                  use_pygments: True