site_name: Your Documentation
site_author: Devansh Agarwal, Kshitij Agarwal
docs_dir: sources
site_description: 'Your Documentation'
repo_name: your
repo_url: https://github.com/thepetabyteproject/your

theme:
  name: material
  palette:
    primary: black
  features:
    - search.highlight

nav:
  - Getting Started: index.md
  - Reading Files: ipynb/Reader.ipynb
  - Writing Files: ipynb/Writer.ipynb
  - Candidates: ipynb/Candidate.ipynb
  - RFI Mitigation: ipynb/RFI.ipynb
  - Command Line Scripts: cli.md
  - Reference API:
      - Core:
          - Your: your.md
          - Candidate: candidate.md
          - Writer: writer.md
      - Formats:
          - Psrdada: formats/psrdada.md
          - Filterbank: formats/pysigproc.md
          - Psrfits: formats/psrfits.md
          - FilWriter: formats/filwriter.md
          - FitsWriter: formats/fitswriter.md
      - Utils:
          - RFI: utils/rfi.md
          - Astro: utils/astro.md
          - Plotter: utils/plotter.md
          - GPU: utils/gpu.md
          - Heimdall: utils/heimdall.md
          - Math: utils/math.md
          - Misc: utils/misc.md
      - CLI:
          - your_bandpass.py: bin/your_bandpass.md
          - your_candmaker.py: bin/your_candmaker.md
          - your_combine_mocks.py: bin/your_combine_mocks.md
          - your_h5plotter.py: bin/your_h5plotter.md
          - your_header.py: bin/your_header.md
          - your_heimdall.py: bin/your_heimdall.md
          - your_rfimask.py: bin/your_rfimask.md
          - your_writer.py: bin/your_writer.md
          - your_viewer.py: bin/your_viewer.md
  - Contributing Guide: CONTRIBUTING.md

plugins:
  - search
  - mkdocs-jupyter:
      include_source: True
      execute: False

markdown_extensions:
  - codehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition

google_analytics:
  - UA-167281386-1
  - auto

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/devanshkv
      name: Devansh Agarwal on Twitter
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/KshitijAgg13
      name: Kshitij agarwal on Twitter

